### ISSUE TITLE
How to get rid of stump? 

### ISSUE THREAD

**Issue by TheDarkPanther** [ivangeevo/btwr-core#10]
I can't seem to get rid of the stump after cutting the tree is there a way to?? 
![2024-08-31_11 13 04](https://github.com/user-attachments/assets/4155d64d-60b6-43a7-8453-8fbbb0d38527)

**Comment by ivangeevo** [comment]
Stumps are removed with Stump Remover item. Please refrain from posting such simple questions which could be easily googled. Also this is the BTWR:Core issue tracker and stumps are from the Sturdy Trees mod.
