### ISSUE TITLE
Mod incompatibility with MoreTools, results in a crash

### ISSUE THREAD

**Issue by Classy-Cube** [ivangeevo/btwr-core#12]
[MoreTools](https://modrinth.com/mod/more-tools) adds a saw which harvests logs above the mined log; a crash occurs when BTWR: Core is installed and a saw is used to mine any wood log type, except oak. 
I believe in my [crash log](https://paste.ee/p/xvDQq#s=0&l=300) the cause of the crash starts at line 300. 
I posted an [issue](https://github.com/JongWasTaken/moretools/issues/16) to MoreTools’s GitHub about this bug as well. 
Only mods installed: `btwr-core-0.25.2-1.20.1.jar` `fabric-api-0.92.2+1.20.1.jar` `moretools-1.5.0+1.20.1.jar`
I’d be grateful if you could take a look at this problem when you have some time.

https://github.com/user-attachments/assets/ff8f2d41-bd7b-459d-9841-00b6a494f239

**Comment by ivangeevo** [comment]
Unfortunately the development for older versions is no longer supported.

**Comment by Classy-Cube** [comment]
That makes sense that you’re not supporting older versions anymore. Thanks anyway.
