### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Kimizuky** [ivangeevo/btwr-core#13]
Are there plans to port the hunger system from btw, with the hunger bar animations?

**Comment by ivangeevo** [comment]
Please don't open issues to ask questions. I will not respond to such anymore out of common sense.
If you want to ask me anything about the mod you can do so in
 My discord: https://discord.gg/3GStyUUXuC
 The #btw-remastered channel in the official BTW Discord
 
But yes, there are a few mods in development that will modify the game in this direction.
